### ISSUE TITLE
Loading cover art while scrolling locks up the GUI, preventing further scrolling until the cover art is loaded

### ISSUE THREAD

**Issue by robbert-vdh** [mixxxdj/mixxx#11128]
### Bug Description

I already asked about this in [Zulip](https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/loading.20covert.20art.20while.20scrolling.20locks.20up.20the.20UI), but I realized I should probably create a bug report so it doesn't get lost. When the cover art column is visible and you scroll through the tracks list, any time the placeholders are being replaced by the actual cover art images fetched from the audio files the UI completely freezes for a short amount of time. The time this takes likely depends on the store the media is stored on, and depending on how the parsing works maybe also on the file size and file type. Loading all media from (relatively fast) mechanical storage, I've seen these hickups last from a hundred milliseconds all the way to almost a second. If you continuously scroll up or downwards then the issue likely either won't appear because you're scrolling fast enough that the placeholders are never replaced, or slow enough that only a couple placeholders are replaced at a time. The issue is most noticeable when scrolling several pages at a time using a traditional mouse scroll wheel. I'd attach a screencast but It's difficult to visualize the delay without doing the scrolling yourself.

### Version

main branch, 3aa2318

### OS

Arch Linux

**Comment by daschuer** [comment]
We had a similar bug:  
https://github.com/mixxxdj/mixxx/issues/10223

"Fixed" here: https://github.com/mixxxdj/mixxx/pull/4904
Maybe there is something else blocking.

**Comment by robbert-vdh** [comment]
Yeah it still happens on the current main branch. I have to hide the cover art column to be able to comfortably scroll through my library.

**Comment by ronso0** [comment]
@robbert-vdh 
I remember a bug where the _aspect ratio_ of the cover was relevant (width of column).
Can you rule that out?

**Comment by robbert-vdh** [comment]
@ronso0 As in, the aspect ratio of the actual column, not the cover art itself? By default Mixxx makes the column to a pretty wide aspect ratio for me if the column is already visible when Mixxx is loaded: 
![image](https://user-images.githubusercontent.com/748520/208154305-652f7f17-5eea-4155-be2e-45f35941800f.png)

If I disable the column, completely restart Mixxx, and re-enable it the column defaults to a square aspect ratio like you'd expect:

![image](https://user-images.githubusercontent.com/748520/208154573-06600488-788d-49bf-915b-9350a94826b5.png)

There however doesn't seem to be any difference in performance between the two sizes and other wider aspect ratios. I'm having over half second pauses scrolling through my library, and if I use the big library mode it takes well over a second before I can continue scrolling.

**Comment by mxmilkiib** [comment]
I'm getting this with 2.5-alpha.

It's about the most obvious and frustrating bug Mixxx has imo.
(The other one probably doing anything whilst Analysing, which is of a similar essence)

**Comment by arximboldi** [comment]
Reproduced in 2.4.1

**Comment by ronso0** [comment]
There is a fix ready to be merged I think #13719
