### ISSUE TITLE
Icecast does not work all.

### ISSUE THREAD

**Issue by kenrestivo** [mixxxdj/mixxx#11236]
![Screenshot 2023-01-30 at 10 27 39 PM](https://user-images.githubusercontent.com/108085/215936837-2e23c399-2024-4147-90b8-b04abd444095.png)
Trying to stream to any icecast2 server (tried a few), from mixxx, does not work.

```
Debug [Main]: DlgPrefBroadcast - broadcastEnabledChanged() 1
Debug [ShoutOutput 'spaz']: ShoutConnection - run: Starting thread
Debug [ShoutOutput 'spaz']: ShoutConnection - processConnect
Debug [ShoutOutput 'spaz']: ShoutConnection - "spaz" : updating from preferences
Debug [ShoutOutput 'spaz']: ShoutConnection - Using server URL: QUrl("//source@radio.spaz.org:8020/stream")
Debug [ShoutOutput 'spaz']: RETURNING SERIAL  1243170195
Warning [ShoutOutput 'spaz']: ShoutConnection - 1 / 3 Streaming server failed connect. Failures: "Please retry current operation."
Warning [ShoutOutput 'spaz']: ShoutConnection - 2 / 3 Streaming server failed connect. Failures: "Please retry current operation."
Warning [ShoutOutput 'spaz']: ShoutConnection - 3 / 3 Streaming server failed connect. Failures: "Please retry current operation."
Debug [ShoutOutput 'spaz']: ShoutConnection - processConnect() returning false
Warning [ShoutOutput 'spaz']: Streaming error:  "Please retry current operation.\nPlease check your connection to the Internet and verify that your username and password are correct."
```

The  message in the screenshot is:
"One of the Live Broadcasting connections raised this error: Error with connecion 'Connection 1' Can't connect to streaming server" "Socker error Please check your connection to the Internet and verify that your username and password are correct.

However, I have absolutely verified that my internet connection and username and password are correct. Also I have verified via a packet dump that mixxx isn't even *trying* to connect. It opens a TCP connection, then immediately closes it! It never sends anything through the connection!

I see you are using the libshout3 library. I modified the example.c in the libshout directory, built it, and tested it, and it does in fact work. Something Mixxx is doing is breaking.

I suspect some kind of race condition bug in Mixxx.

This has been duplicated on both the Mac and Linux versions of released Mixxx.

**Comment by kenrestivo** [comment]
https://github.com/mixxxdj/mixxx/blob/main/src/engine/sidechain/shoutconnection.cpp#L1007 for reference

https://github.com/mixxxdj/mixxx/blob/main/src/engine/sidechain/shoutconnection.cpp#L500

**Comment by daschuer** [comment]
Which version of Mixxxx do you use?

**Comment by daschuer** [comment]
This is likely a duplicate of https://github.com/mixxxdj/mixxx/issues/9681

**Comment by kenrestivo** [comment]
The Linux version was 2.2.4~dfsg-1

I don't know what version was used on the Mac but it was probably the most recent release.

**Comment by daschuer** [comment]
Mixxx 2.2 is no longer supported. Use Mixxx 2.3. 
Can you confirm that the issue if fixed with Mixxx 2.3?

**Comment by jnse** [comment]
I'm also running into this with a fresh build off the latest main branch and bundled libshout.
I tried replacing the bundled libshout_mixxxx.a with a custom build of 2.4.6 but the problem persists - old versions of Mixxx connect fine with the same settings.

**Comment by agrovista** [comment]
mixxx version 2.3.3 on mac os x ventura m1 
will not connect to icecast server
tested on same computer and configuration with Butt connects and streams

**Comment by daschuer** [comment]
Mixxx 2.3.3 does not support macOS Ventura. Please use a developer Snapshot with Ventura support. 
https://downloads.mixxx.org/snapshots/2.3/mixxx-2.3.3-151-g69d6547e73-macosintel.dmg

Alternative you may try an experimental native M1 build of our 2.4-alpha from https://github.com/daschuer/mixxx/tree/arm64-osx-min11.0. But take a backup first just to be sure: https://github.com/mixxxdj/mixxx/wiki/Testing
(The DMG has expired, I will create a fresh one)

**Comment by daschuer** [comment]
Here is the M1 build https://github.com/daschuer/mixxx/suites/10244878232/artifacts/502509291 
(You need to be locked in at GitHub to make the link work)

**Comment by agrovista** [comment]
the M1 2.4 alpha build works, thanks !

**Comment by jnse** [comment]
my test was on Linux though, which was also broken,...

**Comment by daschuer** [comment]
@jnse, is there anything left to do for this issue?

**Comment by jnse** [comment]
Well, it's still broken for me on linux, whether I use the bundled or system libshout...

**Comment by daschuer** [comment]
The system libshout is known broken. 
Please configure Mixxx from the Head of the 2.3 branch in a new build directory. And post your CMake output here.

**Comment by jnse** [comment]
Ah, well, it works fine from the 2.3 branch - but not from the main branch.

**Comment by daschuer** [comment]
There is not a big difference regarding broadcasting between 2.3 and main. Can you share the mixxx.log of a failing run?

**Comment by jnse** [comment]
gah - I'm sorry, we're good - I just checked and the latest main is working for me now - I must have not pulled the latest before or something,... who knows. When it was failing before, the log had:

```Debug [Main]: DlgPrefBroadcast - broadcastEnabledChanged() 0
Debug [Main]: DlgPrefBroadcast - broadcastEnabledChanged() 2
Debug [Main]: DlgPrefBroadcast - broadcastEnabledChanged() 1
Debug [ShoutOutput 'ShadowCouncil']: ShoutConnection - run: Starting thread
Debug [ShoutOutput 'ShadowCouncil']: ShoutConnection - processConnect
Debug [ShoutOutput 'ShadowCouncil']: ShoutConnection - "ShadowCouncil" : updating from preferences
Debug [ShoutOutput 'ShadowCouncil']: ShoutConnection - Using server URL: QUrl("//someuser@redacted:someport/stream")
Debug [ShoutOutput 'ShadowCouncil']: Successfully loaded encoder library  "mp3lame"
Debug [ShoutOutput 'ShadowCouncil']: Loaded libmp3lame version  3.100
Debug [ShoutOutput 'ShadowCouncil']: lame_set_VBR_quality:  "present"  lame_encode_buffer_interleaved_ieee_float:  "present"  id3tag_add_v2:  "present"
Debug [ShoutOutput 'ShadowCouncil']:  CBR mode with bitrate:  128
Warning [ShoutOutput 'ShadowCouncil']: ShoutConnection - 1 / 3 Streaming server failed connect. Failures: "Please retry current operation."
Warning [ShoutOutput 'ShadowCouncil']: ShoutConnection - 2 / 3 Streaming server failed connect. Failures: "Please retry current operation."
Warning [ShoutOutput 'ShadowCouncil']: ShoutConnection - 3 / 3 Streaming server failed connect. Failures: "Please retry current operation."
Debug [ShoutOutput 'ShadowCouncil']: Unloaded libmp3lame 
Debug [ShoutOutput 'ShadowCouncil']: ShoutConnection - processConnect() returning false
Warning [ShoutOutput 'ShadowCouncil']: Streaming error:  "Please retry current operation.\nPlease check your connection to the Internet and verify that your username and password are correct."
```

... but now it's fine.

**Comment by daschuer** [comment]
Thank you for confirming. I am happy we can close this issue.
