### ISSUE TITLE
waveform scrolling

### ISSUE THREAD

**Issue by robi970** [mixxxdj/mixxx#11617]
### Bug Description

I installed Mixxx 2.4 beta and started it.
I quickly realized that the waveforms, spinnys and elapsed time display are displayed as if "4-5 frames per second" is set.

on the same PC I keep Mixxx 2.2.4 installed, which obviously still works perfectly

### Version

2.4 beta

### OS

Win10 pro 64bit - AMD ryzen 5 3600; 16GB ram; AMD radeon R9 200 series

**Comment by JoergAtGithub** [comment]
- Could you please share a screenshot of the Waveforms tab in the Mixxx preferences!
- How much CPU and GPU load does the Windows Task Manger show?
- Did you also tried Mixxx 2.3 builds, or only 2.2 and 2.4 beta?

**Comment by JoergAtGithub** [comment]
Could you please try all waveform types available in the top selector. Does any waveform type shows different frame rates?

**Comment by robi970** [comment]
with all waveforms the value is always around 6.67, except with HSV (FPS: 7.50)

same thing also changing the values ​​of the second selector

(OT question: in this editor is it possible to write in your own language, or do I have to continue with google translate?)

**Comment by JoergAtGithub** [comment]
Please write in English!

**Comment by JoergAtGithub** [comment]
@m0dB Could you have a look

**Comment by JoergAtGithub** [comment]
Does it help if you start with `.\mixxx.exe --disableVuMeterGL`

**Comment by robi970** [comment]
switched to 15 fps

**Comment by m0dB** [comment]
I have no idea, this is very strange and the first time something like this has been reported.

To be sure: 2.3.5 runs as 60 fps?

I will create a build with some logging, but it might take a while, sorry.

**Comment by m0dB** [comment]
Are you having no fps issues with other applications (games)?

Question for @daschuer : are we configuring Qt on windows with 
configure -opengl dynamic ?

**Comment by JoergAtGithub** [comment]
It's dynamic and ANGLE is used when the OPENGL driver is missing or blacklisted by Qt. If ANGLE is used, you see it clearly in the driver information in the waveform preferences.

**Comment by m0dB** [comment]
Thanks, @JoergAtGithub ! So I understand that in this case ANGLE isn't used because a proper OpenGL driver is detected. It might be interesting to see if forcing ANGLE makes a difference, right? Have you ever tried that yourself?

@robi970 can you try running with environment variable QT_OPENGL=angle? Go to the folder where you have your mixxx.exe in the File Explorer, open a command prompt by typing cmd in the address bar, and in the command prompt type:

set QT_OPENGL=angle
mixxx.exe

(Note that I am clutching at straws here, not being a windows user myself)

**Comment by robi970** [comment]
sorry for the delay...

- Mixxx 2.3.5 ran perfectly at 60fps (and Mixxx 2.2.4 still runs perfectly at 60fps)
- tomorrow I will try to open Mixxx as you suggested

**Comment by Swiftb0y** [comment]
Also grasping at straws here, but you mentioned this:
> I installed Mixxx 2.4 beta and started it.
I quickly realized that the waveforms, spinnys and elapsed time display are displayed as if "4-5 frames per second" is set.

I'm pretty sure the elapsed time display is not hardware accelerated so that leads me to believe missing hardware acceleration might not be the problem. Whats your audio buffer size set to?

If I force some weird audio circumstances (mind this is on linux with pipewire, so not quite the same), I can force some low-fps behavior that is not because the waveform rendering is too slow (see the low amount of dropped frames compared to the actual fps) but I think because the update of the playposition depends on the buffer size. Here's a screen recording showing the issue in action: 
[screencast.webm](https://github.com/mixxxdj/mixxx/assets/12380386/c7f90a90-dda0-403c-af61-7ac61de4e5f0)

**Comment by robi970** [comment]
Here you are:
- the end of the prompt list, after following your instructions
![end of long prompt list](https://github.com/mixxxdj/mixxx/assets/135370043/93822de6-cc8d-4b1a-a2ed-5d8e4d99f7f0)

- the warning (unfortunately in Italian) that appears when starting Mixxx:

> "direct rendering" is not enabled on your machine
> 
> this means that displaying waveforms will be very slow and can take a toll on your CPU.
> Update your configuration to enable Direct Rendering, or disable waveform display in Mixxx Preferences by selecting "blank" as waveform display in the "interface" section
![when starting Mixxx](https://github.com/mixxxdj/mixxx/assets/135370043/9c870877-6965-4ce3-bc2c-8d8c86519f40)

**Comment by m0dB** [comment]
Oh, this direct rendering warning is very relevant. Now, how to fix this, I have no idea.

**Comment by robi970** [comment]
since in this editor it is possible to insert videos:

https://github.com/mixxxdj/mixxx/assets/135370043/63cdf889-77a1-46bf-b66a-e89f41630920

**Comment by m0dB** [comment]
Any windows / AMD radeon users who can comment on this? Any idea how to enable Direct Rendering?

**Comment by atskler** [comment]
I can reproduce the problem on a really old HP Compaq 8510P notebook, with Windows 8.1 and with ATI Mobility Radeon HD 2600.

**Comment by m0dB** [comment]
@robi970 can you please try again with a recent 2.4 beta? There was a problem with OpenGL version detection which was was fixed https://github.com/mixxxdj/mixxx/pull/11673 . This fix solved the warning about Direct Rendering for specific Linux drivers, so maybe it also solves it for you on Windows.

**Comment by atskler** [comment]
@m0dB for me the problem is still there with:
2.4-beta-28-g7dcadb17ab (HEAD)
https://github.com/mixxxdj/mixxx/actions/runs/5348576035

**Comment by JoergAtGithub** [comment]
Could you try to set the Windows environment variable QT_NO_OPENGL_BUGLIST (value doesnt matter) before starting Mixxx.
For details see: https://doc.qt.io/qt-5/windows-requirements.html#dynamically-loading-graphics-drivers

**Comment by atskler** [comment]
@JoergAtGithub the problem is the same with:
set QT_NO_OPENGL_BUGLIST=1
mixxx.exe

**Comment by JoergAtGithub** [comment]
Do you have libEGL.dll and libGLESv2.dll in your Mixxx program directory? Could you try to replace these two file with the version from Mixxx 2.3.5?

**Comment by atskler** [comment]
That two dll is there.
The problem is still there with that two dll copied from 2.3.5.

**Comment by JoergAtGithub** [comment]
Thanks for testing! Seems to be a dead end. Maybe you can play with the other environment variables described in: https://doc.qt.io/qt-5/windows-requirements.html#dynamically-loading-graphics-drivers

**Comment by atskler** [comment]
Mixxx also can be started without that two dll and with the 2.4 beta the problem is still there, and 2.3.5 works correctly.

**Comment by JoergAtGithub** [comment]
The are the libraries for the ANGLE emulation of OPENGL. It is used by Qt in case, that the official graphic adapter driver is blacklisted or does not support OPENGL at all. ANGLE is a fast emulation using DirectX.
If Qt could neither find a native OpenGL driver, nor ANGLE, it falls back to Sowtware emulation using the CPU instead of the GPU. It's obvious that your system falls back to this slow software emulation - but I don't know why.

**Comment by JoergAtGithub** [comment]
Could you post a screenshot of the waveform preferences of the working 2.3.5. I would like to see, which graphic system is running there.

**Comment by atskler** [comment]
![DSC_4566__24beta](https://github.com/mixxxdj/mixxx/assets/85284199/1d87aff9-d1ea-4329-8973-18eaeda0bd3d)
![DSC_4565__235](https://github.com/mixxxdj/mixxx/assets/85284199/67b305bb-0b64-4389-8f53-0d1848d53d02)

**Comment by JoergAtGithub** [comment]
In #11673 there was an additional log output for the Supported OpenGL version added, can you search for two lines like this:
```
debug [Main] OpenGL driver version string "4.6.0 Compatibility Profile Context 22.20.28.15.230324", vendor "ATI Technologies Inc.", renderer "AMD Radeon(TM) Graphics"
debug [Main] Supported OpenGL version: 4.6
```

**Comment by atskler** [comment]
```
Debug [Main] OpenGL driver version string "3.3.11672 Compatibility Profile Context", vendor "ATI Technologies Inc.", renderer "ATI Mobility Radeon HD 2600"
Debug [Main] Supported OpenGL version: 3.3
```

**Comment by JoergAtGithub** [comment]
The OpenGL detection code seems to work correct.
Is it possible, that we just raised the minimum required OpenGL version higher than 3.3?

**Comment by atskler** [comment]
> Is it possible, that we just raised the minimum required OpenGL version higher than 3.3?

robi970 has the problem with:
OpenGL 4.6.13559 Compatibility Profile Context 26.20.12028.2 (AMD Radeon R9 200 Series)

**Comment by robi970** [comment]
> @robi970 can you please try again with a recent 2.4 beta? There was a problem with OpenGL version detection which was was fixed #11673 . This fix solved the warning about Direct Rendering for specific Linux drivers, so maybe it also solves it for you on Windows.

I reinstalled Mixxx 2.4 beta, just downloaded [from the site](https://mixxx.org/download/)...  (I hope that is the correct version).
alas no, nothing has changed:

![Mixxx 2 4b](https://github.com/mixxxdj/mixxx/assets/135370043/0d90bf48-478a-4af5-a236-1709148ad134)

**Comment by atskler** [comment]
@JoergAtGithub is there a 2.4 beta build for Windows with QOPENGL=OFF?

**Comment by JoergAtGithub** [comment]
@atskler Can you confirm, that you also get warning dialog at startup shown here: https://github.com/mixxxdj/mixxx/issues/11617#issuecomment-1586179762

**Comment by JoergAtGithub** [comment]
Since you both use AMD GPUs, here are my driver settings. I have 60fps with these settings:
![grafik](https://github.com/mixxxdj/mixxx/assets/64457745/801b7306-3487-4216-835b-5dc77e330a03)
![grafik](https://github.com/mixxxdj/mixxx/assets/64457745/7f84a47f-49bd-4dc7-8e0c-da3bf0366963)
![grafik](https://github.com/mixxxdj/mixxx/assets/64457745/313aa254-9f4d-406f-8fdc-d1a1db58708a)

**Comment by JoergAtGithub** [comment]
I noticed in your screenshots of the waveform preferences, that there is always an exact integer factor between target framerate and the real framerate:
60/6.67= 9
60/12.00=5

Could you try to adjust the target frame rate to other values. Does the integer factor remain?

**Comment by Swiftb0y** [comment]
@robi970 can you check out the newest beta version and look for the line starting with "debug [Main] Supported OpenGL version: " in the debug log? What version does it print exactly?

I'm a little confused because the "Direct Rendering" Warning should only occur if the version is not sufficient. Since the version string does say 4.6 but its not detected correctly, there might be something wrong with the detection logic. 
https://github.com/mixxxdj/mixxx/blob/a5ae80ac68005dc34f9dcc8030d80035b8053238/src/mixxxmainwindow.cpp#L1189-L1194

**Comment by atskler** [comment]
> @atskler Can you confirm, that you also get warning dialog at startup shown here: [#11617 (comment)](https://github.com/mixxxdj/mixxx/issues/11617#issuecomment-1586179762)

Yes, if I start it with:
set QT_OPENGL=angle
mixxx.exe

And Mixxx will not even start, just crashes.
mixxx.exe has stopped working
and once more:
mixxx.exe has stopped working

**Comment by atskler** [comment]
My AMD Catalyst settings:
![catalyst](https://github.com/mixxxdj/mixxx/assets/85284199/708a618a-085d-4544-80e2-ca4719b543ce)

**Comment by JoergAtGithub** [comment]
Can you vary: Wait for vertical refresh

**Comment by atskler** [comment]
> I noticed in your screenshots of the waveform preferences, that there is always an exact integer factor between target framerate and the real framerate: 60/6.67= 9 60/12.00=5
> 
> Could you try to adjust the target frame rate to other values. Does the integer factor remain?

It will differ a bit if the frame rate is odd number. For example 37 will give fluctuating frame rate: 11.43, 11.62.

**Comment by atskler** [comment]
> "Direct Rendering" Warning

@Swiftb0y That warning happens with:
set QT_OPENGL=angle

**Comment by atskler** [comment]
> Can you vary: Wait for vertical refresh

@JoergAtGithub

Frome left to right there are the following options for:

Wait for vertical refresh:

Performance
1) Always off
2) Off, unless application specifies
3) On, unless application specifies
4) Always on
Quality

With option 1) the problem goes away.

**Comment by atskler** [comment]
The warning and the crash with: `set QT_OPENGL=angle` remains.

**Comment by JoergAtGithub** [comment]
> With option 1) the **fps** problem goes away.

Important finding!

The ANGLE issue is an independend issue.

**Comment by robi970** [comment]
@Swiftb0y  the Mixxx version reinstalled yesterday is as follows:

![Image 001](https://github.com/mixxxdj/mixxx/assets/135370043/f153dc3c-5d5f-4def-a8f8-ce0656fad4d1)

**Comment by JoergAtGithub** [comment]
@robi970 Do you have the "Wait for vertical refresh" setting in your AMD driver too? Could you try if it solves the issue for you too?

**Comment by m0dB** [comment]
In the legacy implementation we had this:
```
 243 #if defined(__APPLE__)
 244         // On OS X, syncing to vsync has good performance FPS-wise and
 245         // eliminates tearing.
 246         glFormat.setSwapInterval(1);
 247 #else
 248         // Otherwise, turn VSync off because it could cause horrible FPS on
 249         // Linux.
 250         // TODO(XXX): Make this configurable.
 251         // TODO(XXX): What should we do on Windows?
 252         glFormat.setSwapInterval(0);
 253 #endif
```

I thought I carried this over to the QOpenGL implementation but I see that isn't the case. This might also solve the issue.

**Comment by JoergAtGithub** [comment]
@atskler  @robi970 I created a PR with the potential fix mentioned by m0dB above: https://github.com/mixxxdj/mixxx/pull/11681
Please test, if this works with more options of "Wait for vertical refresh".

**Comment by atskler** [comment]
> @atskler @robi970 I created a PR with the potential fix mentioned by m0dB above: #11681 Please test, if this works with more options of "Wait for vertical refresh".

@JoergAtGithub With the fix only option 4. brings forth the fps problem. With options 1-3 the fps is normal.

@robi970 you will find the installer on the following link for this fixed build, under the "Artifacts" section: https://github.com/mixxxdj/mixxx/actions/runs/5371666174

**Comment by JoergAtGithub** [comment]
> @JoergAtGithub With the fix only option 4. brings forth the fps problem. With options 1-3 the fps is normal.

Great, this is the expected behavior, because "4. Always on" should overwrite the setting inside the application (Mixxx) by definition. Waiting for confirmation by @robi970

**Comment by atskler** [comment]
> Great, this is the expected behavior, because "4. Always on" should overwrite the setting inside the application (Mixxx) by definition. Waiting for confirmation by @robi970

Probably @robi970 should check his gpu settings also if this fix will not work for him, because for example on your system @JoergAtGithub the "Wait for vertical refresh" is set to "Always on". But is that by default? 

Did you managed to reproduce the problem with that setting?

**Comment by JoergAtGithub** [comment]
Today I tried different settings an it always runs with 60fps - I don't remember what the default was, when I initally set it up.
I've to add, that my systems `AMD Ryzen 7 PRO 6850U` contains one of the most powerful mobile GPUs you can get.

**Comment by robi970** [comment]
I fear that I will be forced to wait for new Mixxx releases that better adapt to my system:
I'm too hard, alas, to follow these topics and these instructions with only the use of google translate...

for example: my PC has no Catalyst Pro Control Service

**Comment by JoergAtGithub** [comment]
Just test the latest 2.4 Beta
