### ISSUE TITLE
Analyzed keys are not saved as text

### ISSUE THREAD

**Issue by uklotzde** [mixxxdj/mixxx#13646]
### Bug Description

Neither in the database nor as metadata.

`Keys::getGlobalKeyText()` in `TrackRecord::setKeys()` returns an empty String.

The database contains an empty string in `library.key` and the file tag is missing.

### Version

main

**Comment by Swiftb0y** [comment]
regression from #11096?

**Comment by daschuer** [comment]
I can reproduce the issue with the 2.5 branch but not with 2.4. 

It looks like a nasty issue that the analyzer is not writing the global key text and it has been fixed individually in two places: 
```
void TrackRecord::setKeys(const Keys& keys) {
-    refMetadata().refTrackInfo().setKeyText(KeyUtils::formatGlobalKey(keys));
+    refMetadata().refTrackInfo().setKeyText(keys.getGlobalKeyText());
```

```
void bindTrackLibraryValues(
    ...
-    QString keyText = KeyUtils::formatGlobalKey(keys);
+    QString keyText = keys.getGlobalKeyText();
```

I will prepare a PR

**Comment by FrankwaP** [comment]
Sorry but I still get empty "key" fields in my database  with a compiled Mixxx 2.6.0-alpha (using libkeyfinder).
