### ISSUE TITLE
qhash.h:790 ASSERT on multiple MIDI messages in quick succession

### ISSUE THREAD

**Issue by mxmilkiib** [mixxxdj/mixxx#13940]
### Bug Description

When my script sends multiple MIDI messages in quick succession, it often makes Mixxx trigger an assert;
```
 [Controller] fatal /usr/include/qt6/QtCore/qhash.h:790 ASSERT: "!isUnused()" in file /usr/include/qt6/QtCore/qhash.h, line 790
```

**Comment by mxmilkiib** [comment]
https://gist.github.com/mxmilkiib/9bee33b0ed7113243c9e1a3a14d5ae01
https://gist.github.com/mxmilkiib/6fe50aeaee3200dd1ff2d346f1b2f978#file-launchpadpromk3-js

**Comment by daschuer** [comment]
The assertion violation happens here:
https://github.com/qt/qtbase/blob/4059ea60e52291ca7e2c9086663c3c3e10839090/src/corelib/tools/qhash.h#L790

Probably a race condition?

**Comment by daschuer** [comment]
Which version of Mixxx is affected? 

Please create a Backtraces:
https://github.com/mixxxdj/mixxx/wiki/Creating-Backtraces

Does Mixxx crash?

**Comment by mxmilkiib** [comment]
I should have said, the first link in the last post is what I got from following those instructions (which fwiw could mention `gdb -ex "set height 0"`)

n yes, crashes

I pulled n built before testing, `r2.6-alpha-138-g0eccb1b2db (main)`

**Comment by Swiftb0y** [comment]
Thanks. The crash seems in `MidiController::receivedShortMessage` so your hardware must also be sending at a high rate...

**Comment by daschuer** [comment]
https://github.com/daschuer/mixxx/blob/8b81a37302b68e3b072c96cc1539fe578c34976e/src/controllers/midi/midicontroller.cpp#L290

So the race may happen around: `LegacyMidiControllerMapping::m_inputMappings`
However, there is noting obvious. 

Is this only a side effect and we are using a dangling pointer, because the m_pMapping is already down?
Or is `m_pMapping` still null? 

Al least there are a couple of race conditions happening possible with m_pMapping. 
`std::shared_ptr` is thread safe, but the pointer may change between two calls. 

This means  `m_pMapping->getInputMappings().constEnd()` point to a new mapping while it still points to the old. 
The function needs to become an shared owner first before using the m_pMappings. 

Please try to alter the code to: 
``` 
    // Function becomes temorary shared owner 
    std::shared_ptr<LegacyMidiControllerMapping> pMapping = m_pMapping; 
    if (!pMapping) {
        return; 
    }
    auto it = pMapping->getInputMappings().constFind(mappingKey.key);
    for (; it != pMapping->getInputMappings().constEnd() && it.key() == mappingKey.key; ++it) {
```

**Comment by mxmilkiib** [comment]
Yes, that change seems to solve the problem, thank you!

**Comment by daschuer** [comment]
I have created a PR that aims to fix the issue: 
https://github.com/mixxxdj/mixxx/pull/13980
Please test, and report your results at the PR. 
Thank you.

**Comment by daschuer** [comment]
> what exactly is/was the problem? what part of the process is tripping up?

The problem is that the crashing function is called from the controller thread, before the mapping is fully loaded. In the moment where the mapping is changed, the code starts to iterate on the old mapping, but tries to finish on the new one which fails. 
The solution is to keep the old mapping valid until all users use the new one.

**Comment by mxmilkiib** [comment]
`[Controller] fatal /usr/include/qt6/QtCore/qhash.h:1928 ASSERT: "e && *e" in file /usr/include/qt6/QtCore/qhash.h, line 1928`

**Comment by daschuer** [comment]
Does this happen with https://github.com/mixxxdj/mixxx/pull/13980 
For my understanding this shall fully fix the issue. 
Is the backtrace different now?

**Comment by mxmilkiib** [comment]
yup, [trace](https://gist.github.com/mxmilkiib/11c5b4e91faa9fb8d092a3e7978cf8d2)

**Comment by daschuer** [comment]
I have added more null checks to #13980 Does that make a difference?

**Comment by mxmilkiib** [comment]
still there 

I've figured it can be reproduced when the Mixxx window is not the active window

**Comment by daschuer** [comment]
It looks like you don't use my latest branch. At least the line numbers in the backtrace do not correspond to my PR.  You can receive my changes into a new branch by 

````
git checkout -b daschuer-gh13940 2.5
git pull git@github.com:daschuer/mixxx.git gh13940
```

**Comment by mxmilkiib** [comment]
```
01:21:16 milk@red:~/src/mixxx main ± git checkout -b daschuer-gh13940 2.5
Alias tip: gco -b daschuer-gh13940 2.5
fatal: '2.5' is not a commit and a branch 'daschuer-gh13940' cannot be created from it

01:25:15 milk@red:~/src/mixxx main 130 ± git pull git@github.com:daschuer/mixxx.git gh13940
Alias tip: gpl git@github.com:daschuer/mixxx.git gh13940
From github.com:daschuer/mixxx
 * branch                  gh13940    -> FETCH_HEAD
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint:
hint:   git config pull.rebase false  # merge
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches.

01:25:18 milk@red:~/src/mixxx main 128 ± gco gh13940
Switched to branch 'gh13940'

01:26:17 milk@red:~/src/mixxx gh13940 ± git pull git@github.com:daschuer/mixxx.git gh13940
Alias tip: gpl git@github.com:daschuer/mixxx.git gh13940
From github.com:daschuer/mixxx
 * branch                  gh13940    -> FETCH_HEAD
Already up to date.

01:26:56 milk@red:~/src/mixxx gh13940 127 ± gl
commit 3d045698e42db3cec38dc037039eff4b4de81e59 (HEAD -> gh13940)
Author: Daniel Schürmann <daschuer@mixxx.org>
Date:   Mon Dec 9 07:44:01 2024 +0100

    Add more null checks
...
```

**Comment by daschuer** [comment]
Your checkout looks correct. 

The most interesting entry in your recent backtrace is this:
```
#10 MidiController::receivedShortMessage (this=<optimized out>, status=<optimized out>, control=<optimized out>, value=127 '\177', timestamp=...) at /home/milk/src/mixxx/src/controllers/midi/midicontroller.cpp:308
        channel = <optimized out>
        opCode = <optimized out>
        __PRETTY_FUNCTION__ = "virtual void MidiController::receivedShortMessage(unsigned char, unsigned char, unsigned char, mixxx::Duration)"
        mappingKey = {{key = 27824, {status = 176 '\260', control = 108 'l'}}}
        pMapping = std::shared_ptr<LegacyMidiControllerMapping> (use count 130, weak count 0) = {get() = <optimized out>}
        it = {i = {d = <optimized out>, bucket = <optimized out>}, e = 0x7fff2c60a558}
```

A reference count of 130 does not look reasonable. 
So my guess is that the smart pointer is dangling. 

At this line, we have a return statement not a crashing call. 

https://github.com/mixxxdj/mixxx/blob/3d045698e42db3cec38dc037039eff4b4de81e59/src/controllers/midi/midicontroller.cpp#L308

So can you try to build again and reproduce the crash?

**Comment by daschuer** [comment]
Ah, got it, you have probably posted the same backtrace again. At least I can see no difference.

**Comment by mxmilkiib** [comment]
hmm, I copied straight from the terminal as it output (clicked and held and waited for the output and let it do the dragging n made sure it got all then middle click pasted as a second file to the same gist entry, though the link above should have been just to the new log not to both of them) 

thanks, I'll try again in a while

**Comment by mxmilkiib** [comment]
done, [trace](https://gist.github.com/mxmilkiib/b565bdf9bf6681b778140432fb99caf0)

**Comment by daschuer** [comment]
Ah now it fits, thank you ... but still crashing :-(
```
#10 MidiController::receivedShortMessage (this=<optimized out>, status=<optimized out>, control=<optimized out>, value=127 '\177', timestamp=...) at /home/milk/src/mixxx/src/controllers/midi/midicontroller.cpp:311
        channel = <optimized out>
        opCode = <optimized out>
        __PRETTY_FUNCTION__ = "virtual void MidiController::receivedShortMessage(unsigned char, unsigned char, unsigned char, mixxx::Duration)"
        mappingKey = {{key = 27824, {status = 176 '\260', control = 108 'l'}}}
        pMapping = std::shared_ptr<LegacyMidiControllerMapping> (use count 123, weak count 0) = {get() = <optimized out>}
        it = {i = {d = <optimized out>, bucket = <optimized out>}, e = 0x7fff2c6cd028}
```

use count =123 is obviously in correct. It starts with use count = 1, asserted here: 
https://github.com/mixxxdj/mixxx/blob/24a84b9d64607bb2b2cdcfc270bf9cb885074f3a/src/controllers/controller.h#L121
and there are not 123 owners. 

Maybe `ControllerManager::updateControllerList()` is called while the controlle is still receiving messages? 
I have added an assertion. Maybe you hit it? 
Please try.

**Comment by mxmilkiib** [comment]
https://gist.github.com/mxmilkiib/22a21982511fdbf36d5169699a99615e

**Comment by mxmilkiib** [comment]
might there be anything further I could do to help diagnose this?

**Comment by mxmilkiib** [comment]
possible this could get another look?

**Comment by daschuer** [comment]
This is the significant part of the backtrace
```
#8  0x00007ffff0091604 in qt_assert (assertion=assertion@entry=0x555555706de4 "e && *e", file=file@entry=0x5555556b2b90 "/usr/include/qt6/QtCore/qhash.h", line=line@entry=1928) at /usr/src/debug/qt6-base/qtbase/src/corelib/global/qassert.cpp:105
#9  0x000055555615f22a in QMultiHash<unsigned short, MidiInputMapping>::const_iterator::operator++ (this=<synthetic pointer>) at /usr/include/qt6/QtCore/qhash.h:1928
#10 MidiController::receivedShortMessage (this=<optimized out>, status=<optimized out>, control=<optimized out>, value=127 '\177', timestamp=...) at /home/milk/src/mixxx/src/controllers/midi/midicontroller.cpp:311
        channel = <optimized out>
        opCode = <optimized out>
        __PRETTY_FUNCTION__ = "virtual void MidiController::receivedShortMessage(unsigned char, unsigned char, unsigned char, mixxx::Duration)"
        mappingKey = {{key = 27824, {status = 176 '\260', control = 108 'l'}}}
        pMapping = std::shared_ptr<LegacyMidiControllerMapping> (use count 123, weak count 0) = {get() = <optimized out>}
        it = {i = {d = <optimized out>, bucket = <optimized out>}, e = 0x7fff2c0411e8}
#11 0x00005555566f10c5 in PortMidiController::poll (this=0x7fff2c0b5fc0) at /home/milk/src/mixxx/src/controllers/midi/portmidicontroller.cpp:153
        note = <optimized out>
        velocity = <optimized out>
        status = 176 '\260'
        timestamp = {<mixxx::DurationBase> = {static kMillisPerSecond = 1000, static kMicrosPerSecond = 1000000, static kNanosPerSecond = 1000000000, static kNanosPerMilli = 1000000, static kNanosPerMicro = 1000, m_durationNanos = <optimized out>}, <No data fields>}
        i = <optimized out>
        numEvents = 1
        __PRETTY_FUNCTION__ = "virtual bool PortMidiController::poll()"
#12 0x0000555555a4a865 in ControllerManager::pollDevices (this=0x5555869ff800) at /home/milk/src/mixxx/src/controllers/controllermanager.cpp:377
        pDevice = 0x7fff2c0b5fc0
        __for_range = <optimized out>
        __for_begin = {i = <optimized out>}
        __for_end = {i = <optimized out>}
        start = {<mixxx::DurationBase> = {static kMillisPerSecond = 1000, static kMicrosPerSecond = 1000000, static kNanosPerSecond = 1000000000, static kNanosPerMilli = 1000000, static kNanosPerMicro = 1000, m_durationNanos = 21469449942}, <No data fields>}
        duration = {<mixxx::DurationBase> = {static kMillisPerSecond = 1000, static kMicrosPerSecond = 1000000, static kNanosPerSecond = 1000000000, static kNanosPerMilli = 1000000, static kNanosPerMicro = 1000, m_durationNanos = <optimized out>}, <No data fields>}
#13 0x00007ffff01b1b29 in QtPrivate::QSlotObjectBase::call (this=0x555586a12160, r=0x5555869ff800, a=0x7fffa3ff5d00, this=<optimized out>, r=<optimized out>, a=<optimized out>) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qobjectdefs_impl.h:486
#14 doActivate<false> (sender=<optimized out>, signal_index=<optimized out>, argv=<optimized out>) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qobject.cpp:4124
        obj = {m_slotObject = std::unique_ptr<QtPrivate::QSlotObjectBase> = {get() = 0x555586a12160}}
        receiver = 0x5555869ff800
        td = <optimized out>
        receiverInSameThread = <optimized out>
        senderData = {previous = 0x0, receiver = 0x5555869ff800, sender = 0x5555869ff828, signal = 3}
        c = 0x7fff38013b70
        connections = {d = <optimized out>}
        list = <optimized out>
        inSenderThread = <optimized out>
        highestConnectionId = <optimized out>
        signalVector = 0x555586a12540
        currentThreadId = <optimized out>
        sp = <optimized out>
        signal_spy_set = 0x0
        empty_argv = {0x0}
        senderDeleted = false
#15 0x00007ffff01bab35 in QTimer::timeout (this=0x5555869ff828, _t1=...) at /usr/src/debug/qt6-base/build/src/corelib/Core_autogen/include/moc_qtimer.cpp:223
        _a = {0x0, 0x7fffa3ff5cf8}
```

**Comment by daschuer** [comment]
I have added more assertions regarding `use_count()` to #13980 
Please reproduce the crash and provide the mixxx.log from the carshing run.

**Comment by daschuer** [comment]
Wait, test is failing which is good.

**Comment by mxmilkiib** [comment]
https://gist.github.com/mxmilkiib/c03f40ffa554341178bfe238cbff3155

**Comment by daschuer** [comment]
I have created https://github.com/mixxxdj/mixxx/pull/14159 which may fix the issue. Please test.
