### ISSUE TITLE
Analyze view: make "New" show tracks with no valid ReplayGain value

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/mixxx#14503]
### Feature Description

Currently, the default "New" filter in the Analyze view shows tracks that have been added in the last 7 days, which may include tracks that have been analyzed.
This makes the "New" filter pretty useless because having added tracks earlier than last week doesn't mean they're old, analyzed, played or prepared.

In the forum discussion the idea came up to find "new" tracks by sorting by 'ReplayGain' column.

How about making the "New" filter show tracks that have no (valid) ReaplyGain value?
Loading a track to a player triggers all analyzers incl. ReplayGain, so tracks are not "new" to Mixxx anymore.

Wdyt?

**Comment by SamWhited** [comment]
I think this will help, but it still feels odd to use a heuristic that won't work for everyone in place of an explicit feature.

Ie. I often load lots of tracks, then analyze them all at once so that Mixxx can be busy doing that in the background and I don't have to wait a few seconds to play the track when I load it up to start sorting it or deciding if it's a keeper or what not. So the replay gain wouldn't work here. I could just stop doing that and wait for each individual track, of course, that's fine, but it still feels like it's not an ideal way to fix the situation since different people will use the replay gain / analyze feature in different ways.

**Comment by JosepMaJAZ** [comment]
I think we first should fix the "New" radio button to actually show recently added tracks.
Then, it could add another "not analysed" button. 
Should this button rely on having replaygain or not? Not sure. I don't remember the database structure right now, and I'm not sure if we can check for the presence of the waveform analisys (without going to the cache, and knowing that the user can opt not to have a cache).

**Comment by ronso0** [comment]
Hmm, I think we're mixing up two different feature here:
* **Analyze**: pick tracks for batch analysis
* **New Tracks**: a pure _'new'_ tracks view, while definition of _'new'_ varies. Could be unplayed [^1], unanalyzed, unrated, not in a crate, .. We already discussed it elsewhere (Zulip? another bug?) Tracks that are [played|analyzed|rated|prepared] would be auto-removed from that view.

And here we're talking about the Analyze feature, not about a real "New Tracks" feature like. Now, the "New" filter button is just a poor bandaid for _'new'_. Bandaid becasue _"younger than 7 days"_ is obviously not a filter that satisfies the real __'new'__ expectations listed above.

I think it would already be a good improvement if we'd use the 'no RepayGain value' filter (or another suitable indicator for 'has analysis data') and maybe rename the _'new'_ button to 'Not analyzed'.
If we find such an indicator we can also consider adding a `analyzed` keyword to the search query parser.

Does that make sense?

[^1]: sort by `played`/`play_count` in Tracks is not reliable due to #14427 (History tracks cleanup/sync)

**Comment by SamWhited** [comment]
> Hmm, I think we're mixing up two different feature here:
> …
> Does that make sense?

I can definitely see these being separated into two separate views, "Analyze" and "New Tracks" or what not, though the analyze view still doesn't seem super useful in that case. What does it provide over searching for nobpm in the all tracks view? Just having an "Analyze" and "Select All" button in the header doesn't seem worth having a whole other view for, those could just show up in every other view too where they'd also be useful.

**Comment by ronso0** [comment]
The Analyze view was created when the track menu didn't have "Analyze"/"Reanalyze" actions, yet.
The 'Analyze' button exposed a function that was only available implictly via track load back then.

"New" currently doesn't filter by 'no bpm', it really just filters by `date_added < 7 days`.

**Comment by SamWhited** [comment]
That was my suspicion; now that we have analyze buttons in multiple places, it seems like the view itself isn't super useful, which is why it made sense to me that it's purpose could be to handle tracks that are newly added to the library. I can see them being separate features too, but if they are I think it would make sense to find some way for the analyze view to be more useful too, right now it's not clear to me that it enables or simplifies any workflows that aren't already possible elsewhere.

**Comment by ronso0** [comment]
Ideas:
(1) New Track view
* we collect the timestamps when a scan is started
* we add a new view in Tracks: New Tracks
* New Tracks view has filter options:
Added [during scan | since | before | between] [select 1st timestamp]  [select 2nd timestamp]
* selecting during scan | since | before | between enables/disables the apropriate timestamps in the timestamp selectors:
   * during scan / since / before: all timestamps available in 1st selector, 2nd is disabled
   * between: 1st and second selector enabled, in 2nd all items equal & earlier than the 1st selected are disabled / removed

(2) If we also add a `prepared` or `analyzed` flag to the db's `library` table, we'd have some options to filter the New view.
We could let the user decide when a track should be considered "prepared": (multiple choice?)
* audio analyzed (BPM, ReplayGain, ..)
* manually set the main Cue
* set at least one hotcue
* adjusted intro/outro
* set the rating
* added track to a playlist / crate

**Comment by SamWhited** [comment]
> We could let the user decide when a track should be considered "prepared": (multiple choice?)

Some combination of these would probably do the job, but I still wonder if it would make more sense to have an explicit "analyzed" flag. When you press the analyze button that flag is set (or more likely a single row is deleted from the "unanalyzed" table which has a single column foreign key to a track so that every single song doesn't end up with a new column which would be significantly more space for a boolean that will get set exactly once, I suspect). Why not just be explicit? Using other, unrelated, features as an indicator just seems like it's going to be painful in somebodies workflow no matter what.
