### ISSUE TITLE
After Ubuntu 25.10. update Mixxx does not install

### ISSUE THREAD

**Issue by DerEber** [mixxxdj/mixxx#15554]
### Bug Description

Maybe something went wrong with my update. My console was freezing during the update but I have no clue how to check things. 
Anyhow mixxx(beta) won't install.
I get the following Error:
```
Nichterfüllte Abhängigkeiten:
 mixxx : Hängt ab von: qt6-base-private-abi (= 6.8.3)
               Hängt ab von: qml6-module-qtquick-nativestyle ist aber nicht installierbar
Fehler: Unable to satisfy dependencies. Reached two conflicting decisions:
   1. mixxx:amd64=2.6~beta~78~gfcf57edd24-1~questing is selected for install
   2. mixxx:amd64=2.6~beta~78~gfcf57edd24-1~questing Hängt ab von qml6-module-qtquick-nativestyle
      but none of the choices are installable:
      [no choices]
```

### Version

2.6

### OS

Ubuntu 25.10

**Comment by ronso0** [comment]
Thanks for the report, there is a fix being worked on #15440

**Comment by DerEber** [comment]
<img width="1765" height="1023" alt="Image" src="https://github.com/user-attachments/assets/a7407ebc-334d-4564-9e96-f4297d575626" />

During the linux update my console stopped at this line.
I did strg-c and a reboot. I had to reset the laptop once, but had no further complains.

**Comment by DerEber** [comment]
With the Version provided in #15440 I get following errors.

<img width="1497" height="958" alt="Image" src="https://github.com/user-attachments/assets/797ed7e8-e178-4604-9aaa-c17b627f6690" />

I'm still not sure if it's a mixxx problem or something went wrong with my linux update.

**Comment by DerEber** [comment]
I checked 2.5.3 and it installs fine

**Comment by daschuer** [comment]
The build provided in https://github.com/mixxxdj/mixxx/pull/15440 is for Ubuntu 24.04

libqt6xml6t64 is has been removed from Qt 6.6 (Ubuntu >= Oracular 24.10)

**Comment by DerEber** [comment]
/Nichterfüllte Abhängigkeiten:
 mixxx : Hängt ab von: qt6-base-private-abi (= 6.8.3)
         Hängt ab von: qml6-module-qtquick-nativestyle ist aber nicht installierbar
Fehler: Unable to satisfy dependencies. Reached two conflicting decisions:
   1. mixxx:amd64=2.6~beta~78~gfcf57edd24-1~questing is selected as an upgrade
   2. mixxx:amd64=2.6~beta~78~gfcf57edd24-1~questing Hängt ab von qml6-module-qtquick-nativestyle
      but none of the choices are installable:
      [no choices]

Still got the same massage but I really wonder why it wants to install 2.6 beta 78
I see beta 123 here:
https://launchpad.net/~mixxx/+archive/ubuntu/mixxxbetas/+packages

**Comment by ronso0** [comment]
> Still got the same massage but I really wonder why it wants to install 2.6 beta 78
I see beta 123 here:
https://launchpad.net/~mixxx/+archive/ubuntu/mixxxbetas/+packages

Because the 123 build for 25.10 (Questing Quokka) failed. (and probably many before)
Need to wait for the 124 build which finished but still needs to be published
<img width="1138" height="535" alt="Image" src="https://github.com/user-attachments/assets/7fd8573a-8805-415b-a136-bb8b540ed8a3" />

**Comment by DerEber** [comment]
Works!!! :)

**Comment by ronso0** [comment]
Great!

**Comment by djtulan** [comment]
The same dependency problem exists for mixxx version 2.5.4-1 on ubuntu 25.10.

`mixxx:amd64=2.5.4-1~questing depends on qml6-module-qtquick-nativestyle`

**Comment by daschuer** [comment]
Oh that's bad. I think we need to do a patch release for this.

**Comment by s-light** [comment]
just stumble about the same with the official ppa install instructions:
`kubuntu 25.10`

```bash
$ sudo asudo apt install mixxx
Solving dependencies... Error!  
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

Unsatisfied dependencies:
 mixxx : Depends: libhidapi-hidraw0 (>= 0.10.0+dfsg) but it is not going to be installed
         Depends: libshout-idjc3 (>= 2.4.6-r1) but it is not going to be installed
         Depends: fonts-open-sans but it is not going to be installed
         Depends: qml6-module-qtquick-nativestyle but it is not installable
Error: Unable to satisfy dependencies. Reached two conflicting decisions:
   1. mixxx:amd64=2.5.4-1~questing is selected for install
   2. mixxx:amd64=2.5.4-1~questing Depends qml6-module-qtquick-nativestyle
      but none of the choices are installable:
      [no choices]
```

**Comment by benoit-cty** [comment]
As far as I understand, the issue is fixed in 2.6 branch but there is no 2.6 release yet.

**Comment by s-light** [comment]
the beta version is working!

**Comment by ronso0** [comment]
@daschuer so we need to backport #15440 to 2.5?

**Comment by daschuer** [comment]
Oh I see it is also in 2.5: 
https://github.com/daschuer/mixxx/blob/fc945861dc18a526662fc8686cbdfb7239190ec0/CMakeLists.txt#L4009
Yes we need to remove that line and can upload a patched version of our release.

**Comment by ronso0** [comment]
@daschuer I'm confused. Did you already fix it?
I don't find that line in https://github.com/mixxxdj/mixxx/blob/2.5/CMakeLists.txt

**Comment by daschuer** [comment]
I was the one that was confused. I have tried to fix this, but the Launchpad build failed for another reason. I am in progress of another attempt.

**Comment by daschuer** [comment]
This issue is fixed now. We have a 2.5.4-3.

**Comment by ronso0** [comment]
Thank you for taking care!

**Comment by djtulan** [comment]
I'm sorry to say, but it is still not working.

if you have a look to this:
`https://launchpadlibrarian.net/841990878/mixxx_2.5.4-2~questing_2.5.4-3~questing.diff.gz
`
the dependency is removed from CMakeLists.txt, but somehow it is still added to the debian package:

```
-Depends: ${shlibs:Depends}, ${misc:Depends}, fonts-open-sans, fonts-ubuntu, libqt6sql6-sqlite, qt6-qpa-plugins, qml6-module-qt5compat-graphicaleffects, qml6-module-qtquick-controls, qml6-module-qtquick-layouts, qml6-module-qtquick-templates, qml6-module-qtquick-window, qml6-module-qt-labs-qmlmodels, qml6-module-qtquick-shapes, qml6-module-qtqml-workerscript
+Depends: ${shlibs:Depends}, ${misc:Depends}, fonts-open-sans, fonts-ubuntu, libqt6sql6-sqlite, qt6-qpa-plugins, qml6-module-qt5compat-graphicaleffects, qml6-module-qtquick-controls, qml6-module-qtquick-layouts, qml6-module-qtquick-nativestyle, qml6-module-qtquick-templates, qml6-module-qtquick-window, qml6-module-qt-labs-qmlmodels, qml6-module-qtquick-shapes, qml6-module-qtqml-workerscript
```

**Comment by daschuer** [comment]
Ups. I have missed the point that the control file was created before the patch has been applied.
Uploaded patch version 4. I hope this finally does the trick.

**Comment by djtulan** [comment]
This one works now! Thank you Daniel Schürmann for the fix!
